export const testsTypes = {
  // Sync
  GET_TESTS_REQUEST: 'TESTS|GET_TESTS_REQUEST',
  GET_TESTS_SUCCESS: 'TESTS|GET_TESTS_SUCCESS',
  GET_TESTS_FAILED: 'TESTS|GET_TESTS_FAILED',

  GET_SINGLE_TEST_REQUEST: 'TESTS|GET_SINGLE_TEST_REQUEST',
  GET_SINGLE_TEST_SUCCESS: 'TESTS|GET_SINGLE_TEST_SUCCESS',
  GET_SINGLE_TEST_FAILED: 'TESTS|GET_SINGLE_TEST_FAILED',

  EDIT_SINGLE_TEST_REQUEST: 'TESTS|EDIT_SINGLE_TEST_REQUEST',
  EDIT_SINGLE_TEST_SUCCESS: 'TESTS|EDIT_SINGLE_TEST_SUCCESS',
  EDIT_SINGLE_TEST_FAILED: 'TESTS|EDIT_SINGLE_TEST_FAILED',
  EDIT_TEST_ASYNC: 'TESTS|EDIT_SINGLE_TEST_TEST_ASYNC',

  DELETE_SINGLE_TEST_REQUEST: 'TESTS|DELETE_SINGLE_TEST_REQUEST',
  DELETE_SINGLE_TEST_SUCCESS: 'TESTS|DELETE_SINGLE_TEST_SUCCESS',
  DELETE_SINGLE_TEST_FAILED: 'TESTS|DELETE_SINGLE_TEST_FAILED',
  DELETE_SINGLE_TEST_ASYNC: 'TESTS|DELETE_SINGLE_TEST_TEST_ASYNC',

  CREATE_TEST_REQUEST: 'TESTS|CREATE_TEST_REQUEST',
  CREATE_TEST_SUCCESS: 'TESTS|CREATE_TEST_SUCCESS',
  CREATE_TEST_FAILED: 'TESTS|CREATE_TEST_FAILED',
  CREATE_TEST_ASYNC: 'TESTS|CREATE_TEST_ASYNC',

  ADD_QUESTION_REQUEST: 'TESTS|ADD_QUESTION_REQUEST',
  ADD_QUESTION_SUCCESS: 'TESTS|ADD_QUESTION_SUCCESS',
  ADD_QUESTION_FAILED: 'TESTS|ADD_QUESTION_FAILED',
  ADD_QUESTION_ASYNC: 'TESTS|ADD_QUESTION_ASYNC',

  ADD_FILE_REQUEST: 'TESTS|ADD_FILE_REQUEST',
  ADD_FILE_SUCCESS: 'TESTS|ADD_FILE_SUCCESS',
  ADD_FILE_FAILED: 'TESTS|ADD_FILE_FAILED',
  ADD_FILE_ASYNC: 'TESTS|ADD_FILE_ASYNC',

  DELETE_FILE_REQUEST: 'TESTS|DELETE_FILE_REQUEST',
  DELETE_FILE_SUCCESS: 'TESTS|DELETE_FILE_SUCCESS',
  DELETE_FILE_FAILED: 'TESTS|DELETE_FILE_FAILED',
  DELETE_FILE_ASYNC: 'TESTS|DELETE_FILE_ASYNC',

  DELETE_QUESTION_REQUEST: 'TESTS|DELETE_QUESTION_REQUEST',
  DELETE_QUESTION_SUCCESS: 'TESTS|DELETE_QUESTION_SUCCESS',
  DELETE_QUESTION_FAILED: 'TESTS|DELETE_QUESTION_FAILED',
  DELETE_QUESTION_ASYNC: 'TESTS|DELETE_QUESTION_ASYNC',

  EDIT_QUESTION_REQUEST: 'TESTS|EDIT_QUESTION_REQUEST',
  EDIT_QUESTION_SUCCESS: 'TESTS|EDIT_QUESTION_SUCCESS',
  EDIT_QUESTION_FAILED: 'TESTS|EDIT_QUESTION_FAILED',
  EDIT_QUESTION_ASYNC: 'TESTS|EDIT_QUESTION_ASYNC',

  GET_QUESTION_REQUEST: 'TESTS|GET_QUESTION_REQUEST',
  GET_QUESTION_SUCCESS: 'TESTS|GET_QUESTION_SUCCESS',
  GET_QUESTION_FAILED: 'TESTS|GET_QUESTION_FAILED',
  GET_QUESTION_ASYNC: 'TESTS|GET_QUESTION_ASYNC',

  GET_RESULTS_REQUEST: 'TESTS|GET_RESULTS_REQUEST',
  GET_RESULTS_SUCCESS: 'TESTS|GET_RESULTS_SUCCESS',
  GET_RESULTS_FAILED: 'TESTS|GET_RESULTS_FAILED',
  GET_RESULTS_ASYNC: 'TESTS|GET_RESULTS_ASYNC',

  SET_RESULTS_REQUEST: 'TESTS|SET_RESULTS_REQUEST',
  SET_RESULTS_SUCCESS: 'TESTS|SET_RESULTS_SUCCESS',
  SET_RESULTS_FAILED: 'TESTS|SET_RESULTS_FAILED',
  SET_RESULTS_ASYNC: 'TESTS|SET_RESULTS_ASYNC',

  GET_QUESTIONS_REQUEST: 'TESTS|GET_QUESTIONS_REQUEST',
  GET_QUESTIONS_SUCCESS: 'TESTS|GET_QUESTIONS_SUCCESS',
  GET_QUESTIONS_FAILED: 'TESTS|GET_QUESTIONS_FAILED',
  GET_QUESTIONS_ASYNC: 'TESTS|GET_QUESTIONS_ASYNC',

  GET_QUESTION_GROUP_REQUEST: 'TESTS|GET_QUESTION_GROUP_REQUEST',
  GET_QUESTION_GROUP_SUCCESS: 'TESTS|GET_QUESTION_GROUP_SUCCESS',
  GET_QUESTION_GROUP_FAILED: 'TESTS|GET_QUESTION_GROUP_FAILED',
  GET_QUESTION_GROUP_ASYNC: 'TESTS|GET_QUESTION_GROUP_ASYNC',

  SET_SUBTESTS_SUCCESS: 'TESTS|SET_SUBTESTS_SUCCESS',

  SET_PAGE_SUCCESS: 'TESTS|SET_PAGE_SUCCESS',
  SET_FILTER_SUCCESS: 'TESTS|SET_FILTER_SUCCESS',

  // Async
  GET_SINGLE_TEST_ASYNC: 'TESTS|GET_SINGLE_TEST_ASYNC',
  EDIT_SINGLE_TEST_ASYNC: 'TESTS|EDIT_SINGLE_TEST_ASYNC',
  GET_TESTS_ASYNC: 'TESTS|GET_TESTS_ASYNC',
  SET_PAGE_ASYNC: 'TESTS|SET_PAGE_ASYNC',
  SET_FILTER_ASYNC: 'TESTS|SET_FILTER_ASYNC',
};
