export const legalEntitiesTypes = {
  GET_LEGAL_ENTITIES_REQUEST: 'GET_LEGAL_ENTITIES_REQUEST',
  GET_LEGAL_ENTITIES_SUCCESS: 'GET_LEGAL_ENTITIES_SUCCESS',
  GET_LEGAL_ENTITIES_FAILED: 'GET_LEGAL_ENTITIES_FAILED',

  GET_LEGAL_ENTITIE_SINGLE_REQUEST: 'GET_LEGAL_ENTITIE_SINGLE_REQUEST',
  GET_LEGAL_ENTITIE_SINGLE_SUCCESS: 'GET_LEGAL_ENTITIE_SINGLE_SUCCESS',
  GET_LEGAL_ENTITIE_SINGLE_FAILED: 'GET_LEGAL_ENTITIE_SINGLE_FAILED',

  SET_PAGE_SUCCESS: 'LEGAL_ENTITIES|SET_PAGE_SUCCESS',
  SET_FILTER_SUCCESS: 'LEGAL_ENTITIES|SET_FILTER_SUCCESS',
  SET_PAGE_ASYNC: 'LEGAL_ENTITIES|SET_PAGE_ASYNC',
  SET_FILTER_ASYNC: 'LEGAL_ENTITIES|SET_FILTER_ASYNC',

  CREATE_LEGAL_ENTITIE_REQUEST: 'CREATE_LEGAL_ENTITIE_REQUEST',
  CREATE_LEGAL_ENTITIE_SUCCESS: 'CREATE_LEGAL_ENTITIE_SUCCESS',
  CREATE_LEGAL_ENTITIE_FAILED: 'CREATE_LEGAL_ENTITIE_FAILED',
  CREATE_LEGAL_ENTITIE_ASYNC: 'CREATE_LEGAL_ENTITIE_ASYNC',

  EDIT_LEGAL_ENTITIE_REQUEST: 'EDIT_LEGAL_ENTITIE_REQUEST',
  EDIT_LEGAL_ENTITIE_SUCCESS: 'EDIT_LEGAL_ENTITIE_SUCCESS',
  EDIT_LEGAL_ENTITIE_FAILED: 'EDIT_LEGAL_ENTITIE_FAILED',
  EDIT_LEGAL_ENTITIE_ASYNC: 'EDIT_LEGAL_ENTITIE_ASYNC',

  DELETE_LEGAL_ENTITIE_REQUEST: 'DELETE_LEGAL_ENTITIE_REQUEST',
  DELETE_LEGAL_ENTITIE_SUCCESS: 'DELETE_LEGAL_ENTITIE_SUCCESS',
  DELETE_LEGAL_ENTITIE_FAILED: 'DELETE_LEGAL_ENTITIE_FAILED',
  DELETE_LEGAL_ENTITIE_ASYNC: 'DELETE_LEGAL_ENTITIE_ASYNC',

  GET_LEGAL_ENTITIE_SINGLE_ASYNC: 'GET_LEGAL_ENTITIE_SINGLE_ASYNC',
  GET_LEGAL_ENTITIES_ASYNC: 'GET_LEGAL_ENTITIES_ASYNC',
};
