export const problemsTypes = {
  GET_PROBLEMS_REQUEST: 'PROBLEMS|GET_PROBLEMS_REQUEST',
  GET_PROBLEMS_SUCCESS: 'PROBLEMS|GET_PROBLEMS_SUCCESS',
  GET_PROBLEMS_FAILED: 'PROBLEMS|GET_PROBLEMS_FAILED',
  GET_PROBLEMS_ASYNC: 'PROBLEMS|GET_PROBLEMS_ASYNC',

  ADD_PROBLEMS_REQUEST: 'PROBLEMS|ADD_PROBLEMS_REQUEST',
  ADD_PROBLEMS_SUCCESS: 'PROBLEMS|ADD_PROBLEMS_SUCCESS',
  ADD_PROBLEMS_FAILED: 'PROBLEMS|ADD_PROBLEMS_FAILED',
  ADD_PROBLEMS_ASYNC: 'PROBLEMS|ADD_PROBLEMS_ASYNC',

  EDIT_PROBLEMS_REQUEST: 'PROBLEMS|EDIT_PROBLEMS_REQUEST',
  EDIT_PROBLEMS_SUCCESS: 'PROBLEMS|EDIT_PROBLEMS_SUCCESS',
  EDIT_PROBLEMS_FAILED: 'PROBLEMS|EDIT_PROBLEMS_FAILED',
  EDIT_PROBLEMS_ASYNC: 'PROBLEMS|EDIT_PROBLEMS_ASYNC',

  ADD_VIDEOS_REQUEST: 'PROBLEMS|ADD_VIDEOS_REQUEST',
  ADD_VIDEOS_SUCCESS: 'PROBLEMS|ADD_VIDEOS_SUCCESS',
  ADD_VIDEOS_FAILED: 'PROBLEMS|ADD_VIDEOS_FAILED',
  ADD_VIDEOS_ASYNC: 'PROBLEMS|ADD_VIDEOS_ASYNC',

  ADD_PROCESSING_REQUEST: 'PROBLEMS|ADD_PROCESSING_REQUEST',
  ADD_PROCESSING_SUCCESS: 'PROBLEMS|ADD_PROCESSING_SUCCESS',
  ADD_PROCESSING_FAILED: 'PROBLEMS|ADD_PROCESSING_FAILED',
  ADD_PROCESSING_ASYNC: 'PROBLEMS|ADD_PROCESSING_ASYNC',

  EDIT_PROCESSING_REQUEST: 'PROBLEMS|EDIT_PROCESSING_REQUEST',
  EDIT_PROCESSING_SUCCESS: 'PROBLEMS|EDIT_PROCESSING_SUCCESS',
  EDIT_PROCESSING_FAILED: 'PROBLEMS|EDIT_PROCESSING_FAILED',
  EDIT_PROCESSING_ASYNC: 'PROBLEMS|EDIT_PROCESSING_ASYNC',

  GET_PROCESSING_REQUEST: 'PROBLEMS|GET_PROCESSING_REQUEST',
  GET_PROCESSING_SUCCESS: 'PROBLEMS|GET_PROCESSING_SUCCESS',
  GET_PROCESSING_FAILED: 'PROBLEMS|GET_PROCESSING_FAILED',
  GET_PROCESSING_ASYNC: 'PROBLEMS|GET_PROCESSING_ASYNC',

  GET_SINGLE_PROBLEM_REQUEST: 'PROBLEMS|GET_SINGLE_PROBLEM_REQUEST',
  GET_SINGLE_PROBLEM_SUCCESS: 'PROBLEMS|GET_SINGLE_PROBLEM_SUCCESS',
  GET_SINGLE_PROBLEM_FAILED: 'PROBLEMS|GET_SINGLE_PROBLEM_FAILED',
  GET_SINGLE_PROBLEM_ASYNC: 'PROBLEMS|GET_SINGLE_PROBLEM_ASYNC',

  DELETE_SINGLE_PROBLEM_REQUEST: 'PROBLEMS|DELETE_SINGLE_PROBLEM_REQUEST',
  DELETE_SINGLE_PROBLEM_SUCCESS: 'PROBLEMS|DELETE_SINGLE_PROBLEM_SUCCESS',
  DELETE_SINGLE_PROBLEM_FAILED: 'PROBLEMS|DELETE_SINGLE_PROBLEM_FAILED',
  DELETE_SINGLE_PROBLEM_ASYNC: 'PROBLEMS|DELETE_SINGLE_PROBLEM_ASYNC',

  GET_SINGLE_PROBLEM_VIDEOS_REQUEST:
    'PROBLEMS|GET_SINGLE_PROBLEM_VIDEOS_REQUEST',
  GET_SINGLE_PROBLEM_VIDEOS_SUCCESS:
    'PROBLEMS|GET_SINGLE_PROBLEM_VIDEOS_SUCCESS',
  GET_SINGLE_PROBLEM_VIDEOS_FAILED: 'PROBLEMS|GET_SINGLE_PROBLEM_VIDEOS_FAILED',
  GET_SINGLE_PROBLEM_VIDEOS_ASYNC: 'PROBLEMS|GET_SINGLE_PROBLEM_VIDEOS_ASYNC',

  SET_PAGE_SUCCESS: 'PROBLEMS|SET_PAGE_SUCCESS',
  SET_FILTER_SUCCESS: 'PROBLEMS|SET_FILTER_SUCCESS',
  SET_PAGE_ASYNC: 'PROBLEMS|SET_PAGE_ASYNC',
  SET_FILTER_ASYNC: 'PROBLEMS|SET_FILTER_ASYNC',
};
